### ISSUE TITLE
这也太垃圾了吧，闪退，报错

### ISSUE THREAD

**Issue by 948911908** [leanflutter/flutter_aliyun_captcha#1]
![1599619989632](https://user-images.githubusercontent.com/19320137/92549544-129f6280-f28c-11ea-83fd-ec2f54252e77.jpg)
我的app appkey和scene都填写正确，却提示我错误。这两个都不填就会有结果返回。然后又过不了后端都校验。垃圾东西，检查完毕

**Comment by lijy91** [comment]
无意义的垃圾问题
