### ISSUE TITLE
android 6 滑块不显示

### ISSUE THREAD

**Issue by letica** [leanflutter/flutter_aliyun_captcha#10]
用示例项目试了也不显示，请问有办法能判断滑块是否正常显示吗？想做个降级处理...

![20210224163600](https://user-images.githubusercontent.com/5069297/108972659-814b6d80-76be-11eb-963e-ff7b1300fa95.jpg)
![20210224163615](https://user-images.githubusercontent.com/5069297/108972666-83adc780-76be-11eb-888d-d5b79fec2a38.jpg)

**Comment by lijy91** [comment]
请更新到 `1.0.3` 吧。这个看起来是旧版本的了

**Comment by letica** [comment]
> 请更新到 `1.0.3` 吧。这个看起来是旧版本的了

项目中用的确实是1.0.3，android 6 滑块显示不出来呢，上面的图忽略。。

**Comment by letica** [comment]
update了代码，本地iOS运行可以正常显示，安装apk到安卓机也没显示诶><

![image](https://user-images.githubusercontent.com/5069297/109115453-13647c00-777a-11eb-977e-b3e48910597a.png)

**Comment by lijy91** [comment]
@letica 已修复，示例项目缺少网络权限
