### ISSUE TITLE
安装app第一次加载的时候css样式加载不出,关掉再次加载就好(偶发,ios,android都出现过)

### ISSUE THREAD

**Issue by BoyYangyang** [leanflutter/flutter_aliyun_captcha#12]
安装app第一次加载的时候css样式加载不出,关掉再次加载就好(偶发,ios,android都出现过)

**Comment by lijy91** [comment]
出现这个问题的原因可能是首次打开未进行网络授权，所以加载失败，可以在相关的页面做个网络监听，授权后调用 refresh 方法进行刷新
