### ISSUE TITLE
Android 7.0上整个滑块显示成黑色

### ISSUE THREAD

**Issue by wenjiang** [leanflutter/flutter_aliyun_captcha#16]
Android 7.0上整个滑块显示成黑色

**Comment by wenjiang** [comment]
![2201662259745_ pic](https://user-images.githubusercontent.com/2468471/188294901-a3dbaeda-96d2-4b38-aa2c-8a9a35b76f9d.jpg)

**Comment by lijy91** [comment]
已修复，请更新到 1.0.5

**Comment by wenjiang** [comment]
我已收到了。。。
