### ISSUE TITLE
工程Andoid跑不起来

### ISSUE THREAD

**Issue by wenjiang** [leanflutter/flutter_aliyun_captcha#17]
* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $

**Comment by lijy91** [comment]
请问项目中的 example 能否正常运行呢？

**Comment by lijy91** [comment]
请先确保网络可翻墙并先尝试运行 exmaple
