### ISSUE TITLE
关于弹窗展现

### ISSUE THREAD

**Issue by letica** [leanflutter/flutter_aliyun_captcha#2]
有两个问题请教一下~

1. 展现可以不用弹窗的形式，而是直接嵌入flutter页面里吗？

2. aliyun更新了[调用方式](https://help.aliyun.com/document_detail/193141.html?spm=a2c4g.11186623.6.554.4add1f3fIjsqxx#title-vxk-9nn-rvb)，可以更新一下html么？

**Comment by lijy91** [comment]
正在更新中，将会作以下调整：

1. 移除验证弹窗的调用形式，改为验证按钮
2. 将支持滑动验证、智能验证（暂不支持刮刮卡等形式）

![Simulator Screen Shot - iPhone 8 - 2020-12-24 at 23 13 34](https://user-images.githubusercontent.com/3889523/103096066-adeef480-463d-11eb-9553-fb61017b2043.png)

**Comment by lijy91** [comment]
@letica  已更新到 1.0.0 版本，请根据 README.md 重新接入
