### ISSUE TITLE
弹框背景变黑问题

### ISSUE THREAD

**Issue by liaoqifeng** [leanflutter/flutter_aliyun_captcha#3]
弹出验证框后把程序切到后台,然后再切回来,透明背景变成黑色问题怎么解决?是webview背景问题引起的! Android真机

**Comment by lijy91** [comment]
应该是的，版本正在升级中，近期将移除弹窗验证的形式，具体参见：https://github.com/leanflutter/flutter_aliyun_captcha/issues/2

**Comment by liaoqifeng** [comment]
大概什么时候升级完成!

**Comment by lijy91** [comment]
周六日会发布新版本

**Comment by liaoqifeng** [comment]
好的,谢谢！

**Comment by lijy91** [comment]
@liaoqifeng 已更新到 1.0.0 版本，请根据 README.md 重新接入
