### ISSUE TITLE
无法自定义滑块宽度

### ISSUE THREAD

**Issue by liaoqifeng** [leanflutter/flutter_aliyun_captcha#4]
改变滑块上级宽度,滑块会出现滚动条,无法自适应!

**Comment by lijy91** [comment]
麻烦提供下你的代码和截图，还有测试的手机型号

**Comment by Godfather6666** [comment]
class FlutterAliyunCaptcha extends StatelessWidget {

  final AliyunCaptchaController _captchaController = AliyunCaptchaController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Color.fromRGBO(0, 0, 0, 0.8),
      body: Container(
        padding: EdgeInsets.symmetric(horizontal: 60.w),
        alignment: Alignment.center,
        child: Container(
          padding: EdgeInsets.all(20.w),
          decoration: BoxDecoration(
            color: Theme.of(context).primaryColor,
            borderRadius: BorderRadius.circular(16.w),
          ),
          child: SizedBox(
            width: 520.w,
            child: Container(
              width: 520.w,
              height: 100.w,
              child: AliyunCaptchaButton(
                controller: _captchaController,
                type: AliyunCaptchaType.slide, // 重要：请设置正确的类型
                option: AliyunCaptchaOption(
                  appKey: '****************',
                  scene: '*****',
                  language: 'cn',
                  // 更多参数请参见：https://help.aliyun.com/document_detail/193141.html
                ),
                onSuccess: (dynamic data) {
                  print(
                      "滑块成功----------------$data"); // {"sig": "...", "token": "..."}
                },
                onFailure: (String failCode) {},
                onError: (String errorCode) {},
              ),
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by Godfather6666** [comment]
![Uploading 0073E9FC2119EEE2248EB803523D221E.jpg…]()

**Comment by Godfather6666** [comment]
![0073E9FC2119EEE2248EB803523D221E](https://user-images.githubusercontent.com/46367344/103201857-ed625d00-492b-11eb-9c4f-49131ae26dba.jpg)

**Comment by Godfather6666** [comment]
这个就是无法自定义宽度的代码和截图，如果宽度不够会出现滚动条

**Comment by Godfather6666** [comment]
设备型号是：华为荣耀8X

**Comment by lijy91** [comment]
刚确认了问题出现的原因，宽度小于 300px 时SDK会将宽度设置为300px。

**Comment by Godfather6666** [comment]
这个问题可以解决吗

**Comment by Godfather6666** [comment]
这个是阿里滑块的问题吗

**Comment by lijy91** [comment]
阿里的SDK做了这个限制，所以无法在插件中解决。

滑块验证：宽度 >= 300px
智能验证：宽度 >= 302px

测出来这两个值是最小宽度的限制值，只能你那边界面做一下调整了。

**Comment by Godfather6666** [comment]
了解了，谢谢
