### ISSUE TITLE
有没有H5那种无痕验证？

### ISSUE THREAD

**Issue by cikichen** [leanflutter/flutter_aliyun_captcha#5]
不需要显示这些滑块按钮，直接回调结果？

**Comment by cikichen** [comment]
![image](https://user-images.githubusercontent.com/1478821/103254564-ba1ddd80-49c0-11eb-8f32-73447d031d10.png)
框体大小没法自适应

```
Container(
                        width: double.infinity,
                        height: 46,
                        margin: EdgeInsets.only(
                          top: 10,
                          bottom: 10,
                        ),
                        child: AliyunCaptchaButton(
```

**Comment by lijy91** [comment]
昨天的 Issue 测试发现，智能验证宽度必须大于 302px
https://github.com/leanflutter/flutter_aliyun_captcha/issues/4#issuecomment-751643408

**Comment by liaoqifeng** [comment]
@lijy91 在captcha.html里面加一个样式就可以自适应了!麻烦更新一下！
.nc-container #nc_1_wrapper {
        width: 100% !important;
 }

**Comment by lijy91** [comment]
@liaoqifeng 宽度自适应效果已经增加，但智能验证的最小高度必须大于44
