### ISSUE TITLE
安桌机键盘弹起后滑块不见，在输入帐号密码后，滑块动画效果没有了.

### ISSUE THREAD

**Issue by Darcy-shinet** [leanflutter/flutter_aliyun_captcha#7]
安桌机键盘弹起后滑块不见，在输入帐号密码后，滑块动画效果没有了.如下图.
![image](https://user-images.githubusercontent.com/39577339/104008656-abb39b00-51e4-11eb-87ce-eeb2a11e2f8b.png)
上图上键盘弹起，滑块不见
![image](https://user-images.githubusercontent.com/39577339/104008760-d9004900-51e4-11eb-9a12-eeb3b0964773.png)
上图为手势已经滑倒方框内，在手抬起时，会出现滑块

**Comment by lijy91** [comment]
@Darcy-shinet 可以提供一下你的代码吗？把隐私部分删除后提供一个可复现的版本。

**Comment by Darcy-shinet** [comment]
> @Darcy-shinet 可以提供一下你的代码吗？把隐私部分删除后提供一个可复现的版本。

更改41行的appkey就可以运行。
[main.txt](https://github.com/leanflutter/flutter_aliyun_captcha/files/5792104/main.txt)
在模拟器上无法复线，在真机上是可以复现的。

**Comment by lijy91** [comment]
@Darcy-shinet 经测试这可能是华为安全键盘的原因导致了这个问题的出现，只要 TextField 设置了 obscureText 为 true 就会出现。你还有其他品牌的手机可以测试一下是否同样存在这个问题？

```
TextField(
  obscureText: true,
)
```

**Comment by lijy91** [comment]
@Darcy-shinet 已修复，请升级到 `1.0.2`
