### ISSUE TITLE
偶现滑块UI异常

### ISSUE THREAD

**Issue by letica** [leanflutter/flutter_aliyun_captcha#9]
正常：
![image](https://user-images.githubusercontent.com/5069297/105674100-f8f07600-5f21-11eb-9b30-efd2a4a6e757.png)

异常：
![image](https://user-images.githubusercontent.com/5069297/105673473-1244f280-5f21-11eb-9517-75d7d1f6f6f7.png)

异常情况下，滑块高度比外层高度小，并且滑动之后背景色没有变绿，请问有遇到过这种情况吗？

**Comment by lijy91** [comment]
在 debug 还是 release mode 下的呢？

**Comment by letica** [comment]
> 在 debug 还是 release mode 下的呢？

release

**Comment by letica** [comment]
![IMB_zcv6lI](https://user-images.githubusercontent.com/5069297/106240036-8db6e480-623e-11eb-9473-354a51443fa0.gif)

**Comment by lijy91** [comment]
Update to `1.0.4`
